# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f356dd44e0de87ac3901921546a68ed2468ba0faf81441b659398f08ff3483a8f92c7cefde32049c856ab2b32cd4b5394d636905b6d402380a789f8200e2ede

test:
  secret_key_base: d587ea76c7e8a158ba3166e00e2bb0204ad11816edfeb830811401a94baeb8a5f6f3129e2b17d13b3e76069103cf2583aff127a5f9713a242c7f547284a03b37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
